services:
  - type: web
    name: your-service-name
    env: node
    plan: free
    buildCommand: |
      npm install
      npx puppeteer install
    startCommand: |
      node scraper.mjs
    branches: 
      - main
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
